import{S as m,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const p="https://pixabay.com/api/",y="47590180-dc1d7afa62bd02f66448b190c";async function g(r,o=1,n=9){const a=`${p}?key=${y}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${o}`;console.log("Generated URL:",a);try{const e=await fetch(a);if(!e.ok)throw console.error(`HTTP Error: ${e.status}`),new Error(`Failed to fetch images: ${e.statusText}`);const t=await e.json();return console.log("API Response:",t),t}catch(e){throw console.error("Fetch Error:",e),e}}let c;function h(r){const o=document.querySelector(".gallery"),n=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:s,views:d,comments:u,downloads:f})=>`
        <a class="gallery-item" href="${e}">
            <img src="${a}" alt="${t}" loading="lazy" />
            <div class="info">
                <p><b>Likes:</b> ${s}</p>
                <p><b>Views:</b> ${d}</p>
                <p><b>Comments:</b> ${u}</p>
                <p><b>Downloads:</b> ${f}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new m(".gallery-item",{captionsData:"alt",captionDelay:250})}function b(){const r=document.querySelector(".gallery");r.innerHTML=""}console.log("main.js loaded");const L=document.querySelector(".search-container"),w=document.querySelector("#search-input"),l=document.createElement("div");l.classList.add("gallery");document.body.append(l);L.addEventListener("click",async r=>{r.preventDefault();const o=w.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!"});return}b(),$();try{const n=await g(o);n.hits.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):h(n.hits)}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{S()}});function $(){const r=document.createElement("div");r.classList.add("loader"),r.textContent="Loading...",document.body.append(r)}function S(){const r=document.querySelector(".loader");r&&r.remove()}
//# sourceMappingURL=index.js.map
